import { useSession } from 'next-auth/react';
import Head from 'next/head';
import Header from '../components/Header/Header';
import Login from '../components/Login';
import { Sidebar } from '../components/Sidebar/Sidebar';

// 3:54:31

export default function Home() {
  const { data: session } = useSession();

  if (!session) return <Login />;

  return (
    <>
      <Head>
        <title>FB Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />

      <main>
        <Sidebar />
        {/* Feed */}
        {/* Widgets */}
      </main>
    </>
  );
}

// export const getServerSideProps = async (context) => {
//   // get the user
//   const session = await getSession(context);

//   return {
//     props: {
//       session,
//     },
//   };
// };
