import Head from 'next/head';
import Header from '../components/Header/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>FB Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />

      <main>
        {/* Sidebar */}
        {/* Feed */}
        {/* Widgets */}
      </main>
    </>
  );
}
